# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "290fb9d90e00854a600ed8edacf64c0f"
name = "StorePulse"
application_url = "https://store-pulse-chi.vercel.app"
embedded = true
handle = "storepulse-store-alert"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/customers-data-request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/customers-redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/shop-redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locations,read_orders,read_products"

[auth]
redirect_urls = [ "https://store-pulse-chi.vercel.app/api/auth/callback" ]

[pos]
embedded = false

[build]
# Push this file's settings to the Partner dashboard on every deploy.
include_config_on_deploy = true
